services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    image: ramekhchhoeng-portfolio:latest
    restart: unless-stopped
    environment:
      - NUXT_APP_BASE_URL=/

